http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager-core
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
url.git://github.com/.insteadof=https://github.com/
url.https://github.com/.insteadof=git://github.com/
credential.helperselector.selected=manager-core
url.https://.insteadof=git://
url.git@github.com:.insteadof=https://github.com/
url.git://.insteadof=https://
user.email=am_matouk@esi.dz
user.name=meriemMat
url.ssh://git@github.com/.insteadof=https://github.com/
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/meriemMat/Admin.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
